# Changes here will be overwritten by Copier
_commit: v0.14.1
_src_path: gh:bhklab/bhklab-project-template
author_email: joshua.siraj@uhn.ca
author_full_name: Joshua Siraj
github_username: JoshuaSiraj
has_additional_authors: false
project_description: Investigating Bias in Auto Segmentation Models
project_name: Auto Seg Bias
project_slug: auto-seg-bias
publish_to_github: false
python_version: '3.12'
repo_location: JoshuaSiraj
